blog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share_by_email, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
"""blog application models."""
from taggit.managers import TaggableManager

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class PublishedManager(models.Manager):
    """A custom Model Manager for Post."""

    def get_queryset(self):
        return super().get_queryset().filter(status='PUBLISHED')


class Post(models.Model):
    """Post model.

    Attributes:
        DRAFT (str):
            Constant used in STATUS_CHOICES.
        PUBLISHED (str):
            Constant used in STATUS_CHOICES.
        STATUS_CHOICES (tuple):
            Choices for 'status'.
        title (CharField):
            Post title.
        slug (SlugField):
            Post slug. Can contain characters, numbers, hyphens, and
            underscores.
        author (ForeignKey):
            Post author.
        body (TextField):
            Post body.
        publish (DateTimeField):
            Post publish.
        created (DateTimeField):
            Post created.
        updated (DateTimeField):
            Post updated.
        status (CharField):
            Post status.
        objects (Manager):
            Default Django object-relation manager.
        published (PublishedManager):
            Custom object-relation manager.
        tags (TaggableManager):
            Post tags manager.
    """
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'
    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default=DRAFT)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.month,
                             self.publish.day, self.slug])


class Comment(models.Model):
    """A user comment model for a post.

    Attributes:
        post (ForeignKey):
            The post to which the comment belongs.
        name (CharField):
            Commenter name.
        email (TextField):
            Commenter email.
        body (TextField):
            Comment body.
        created (DateTimeField):
            The time the comment were created.
        active (BooleanField):
            Comment display state. True - show the comment.
    """
    # A related_name allows access to article comments ('post.comments.all()')
    # , in addition to accessing the article from a comment ('comment.post').
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
"""Custom forms. Types of fields define validation. If entered data is invalid
will be throw forms.ValidationError.
"""
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    """A user comment form for a post."""

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class EmailPostForm(forms.Form):
    """Form for share a Post by email.

    Attributes:
        name (CharField):
            Email sender name.
        email (EmailField):
            Sender email for reply.
        destination (EmailField):
            Recipient's mail.
        comments (CharField):
            Comment for email.
    """
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    destination = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class SearchForm(forms.Form):
    """Search form for posts on the site.

    Attributes:
        query (CharField):
            A CharField with user search query.
    """
    query = forms.CharField(label='')

blog/views.py
from taggit.models import Tag

from django.contrib.postgres.search import TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger
from django.db.models import Count
from django.db.models.functions import Greatest
from django.shortcuts import get_object_or_404, render

from .forms import CommentForm, EmailPostForm, SearchForm
from .models import Post


def post_detail(request, year, month, day, post, similar_posts_number=4):
    """Displays a Post page with comments and a list of similar Posts.

    Args:
        request (HttpRequest):

        year (int):
            Year of Post Published.
        month (int):
            Month of Post Published.
        day (int):
            Day of Post Published.
        post (str):
            Post slug.
        similar_posts_number (int):
            Number of similar posts on a page.

    Returns:
         An HttpResponse.
    """

    post = get_object_or_404(Post, slug=post, status='PUBLISHED',
                             publish__year=year, publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create a comment.
            new_comment = comment_form.save(commit=False)
            # Bind a comment to the current post.
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = CommentForm()

    # Forming a similar posts list.
    post_tags_ids = post.tags.values_list('id', flat=True)

    similar_posts = (Post.published.filter(tags__in=post_tags_ids)
                     .exclude(id=post.id)
                     .annotate(same_tags=Count('tags'))
                     .order_by('-same_tags', '-publish')
                     )[:similar_posts_number]

    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_list(request, tag_slug=None, posts_on_page=3):
    """Displays the main blog page with paginated Post's.

    Args:
        request (HttpRequest):

        posts_on_page (int):
            Post number on one page.
        tag_slug (str):
            Tag for Post filtering.

    Returns:
         An HttpResponse.
    """
    published_posts = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        published_posts = published_posts.filter(tags__in=[tag])

    paginator = Paginator(published_posts, posts_on_page)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        # If the page number passed in the request is greater than the number
        # of existing page numbers.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',
                  {'page': page, 'posts': posts, 'tag': tag})


def post_search(request):
    """Search posts by a query in title or body.

    Args:
        request (HttpRequest):
            Request with search query passed with the GET method.
    Returns:
         An HttpResponse with search results.
    """
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        threshold = 0.003
        # Annotate table strings by SearchVectors and filter by relevance.
        # Using SearchRank for comment ranking.
        results = (Post.objects
                   .annotate(
                        similarity=Greatest(
                            TrigramSimilarity('title', query),
                            TrigramSimilarity('body', query)
                        )
                    )
                   .filter(similarity__gte=threshold)
                   .order_by('-similarity'))
    return render(request, 'blog/post/search_results.html',
                  {'form': form, 'query': query, 'results': results})


def post_share_by_email(request, post_id):
    """Displays a share Post by email page.

    Args:
        request (HttpRequest):

        post_id (int):
            The primary key of the post.

    Returns:
         HttpResponse with a page about the status of the email sending.
    """
    # Get a Post object by id. In theory get_object_or_404 uses Django ORM
    # (objects.get), they are equivalent anyway.
    post = get_object_or_404(Post, id=post_id, status='PUBLISHED')
    sent = False
    sent_failed = False
    if request.method == 'POST':
        # Pass data from request to form for validate.
        form = EmailPostForm(request.POST)
        # List of validation errors contain in forms.errors.
        if form.is_valid():
            # Contain only valid fields.
            cd = form.cleaned_data

            # Sending email.
            # get_absolute_url() returns the path relative from the application
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = (f"{cd['name']} ({cd['email']}) recommends you reading "
                       f"{post.title}")

            message = (f'Read "{post.title}" at {post_url}\n\n'
                       f"{cd['name']}'s comments:{cd['comments']}")

            from_email = 'django.framework.email.test@gmail.com'
            try:
                send_mail(subject, message, from_email, [cd['destination']])
                sent = True
            except Exception:
                sent_failed = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html',
                  {'post': post, 'form': form, 'sent': sent,
                   'sent_failed': sent_failed})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ post.title }}</h1>
  {#  Post tags  #}
  <p class="tags">
    {% for tag in post.tags.all %}
      <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
    {% endfor %}
  </p>
  {#  Published  #}
  <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
  <div>{{ post.body|markdown }}</div>
  {#  Post share  #}
  <p>
    <a href="{% url "blog:post_share" post.id %}">Share this post by email.</a>
  </p>
  {#  Similar posts #}
  {% if similar_posts %}
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
      <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
    {% endfor %}
  {% endif %}
  {#  Comments  #}
  {% with comments.count as total_comments %}
    <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        Comment {{ forloop.counter }} by {{  comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p>There are no comments yet.</p>
  {% endfor %}
  {% if new_comment %}
    <h2>Your comment has been added.</h2>
  {% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
      {{ comment_form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Add comment"></p>
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Blog App{% endblock %}
{% block content %}
  <h1>Blog App</h1>
  {#  Post tags  #}
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}

  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h2>
    <p class="tags">
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      <div> {{ post.body|markdown|truncatewords:5 }}</div>
    {# If results is empty or can't load. #}
    {% empty %}
      <p>There are no result for your query.</p>
    {% endfor %}
  {% else %}
    <p>Type a search query.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/post/search_results.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result {{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
      <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
      <div> {{ post.body|markdown|truncatewords:5 }}</div>
    {# If results is empty or can't load. #}
    {% empty %}
      <p>There are no result for your query.</p>
    {% endfor %}
  {% else %}
    <p>Type a search query.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
    </p>
  {% elif sent_failed %}
    <h1>Service unavailable.</h1>
    <p>
      "{{ post.title }}" was not sent to {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    {# action = ".": sets the current URL of the form. #}
    <form action="." method="post">
      {# Add form object with fields in <p> tags. #}
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}